-- MySQL Script generated by MySQL Workbench
-- Wed May  8 16:55:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedores` (
  `ID_Fornecedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome_Fornecedor` VARCHAR(255) NOT NULL,
  `Tipo_Servico` ENUM('Catering', 'Decoracao', 'Outro') NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Fornecedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usuários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuários` (
  `ID_Usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Tipo_Usuario` ENUM('Cliente', 'proprietario') NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Usuario`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`salões de festas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salões de festas` (
  `ID_Salao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome_Salao` VARCHAR(255) NOT NULL,
  `Localizacao` VARCHAR(255) NOT NULL,
  `Capacidade` INT UNSIGNED NOT NULL,
  `Descricao` TEXT NOT NULL,
  `Preco_Base` DECIMAL(10,2) UNSIGNED NOT NULL,
  `ID_Proprietario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Salao`),
  INDEX `ID_Proprietário_idx` (`ID_Proprietario` ASC) VISIBLE,
  CONSTRAINT `ID_Proprietário`
    FOREIGN KEY (`ID_Proprietario`)
    REFERENCES `mydb`.`usuários` (`ID_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `ID_Reserva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Usuario` INT UNSIGNED NOT NULL,
  `ID_Salao` INT UNSIGNED NOT NULL,
  `Data_Evento` DATE NOT NULL,
  `Status_Reserva` ENUM('Pendente', 'Confirmada', 'Cancelada') NOT NULL,
  `Detalhes_Pagamento` TEXT NOT NULL,
  PRIMARY KEY (`ID_Reserva`),
  INDEX `ID_Usuario_idx` (`ID_Usuario` ASC) VISIBLE,
  INDEX `ID_Salão_idx` (`ID_Salao` ASC) VISIBLE,
  CONSTRAINT `ID_Salão`
    FOREIGN KEY (`ID_Salao`)
    REFERENCES `mydb`.`salões de festas` (`ID_Salao`),
  CONSTRAINT `ID_Usuario`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `mydb`.`usuários` (`ID_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `ID_Evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Reserva` INT UNSIGNED NOT NULL,
  `Tema` VARCHAR(255) NOT NULL,
  `Layout_Assentos` VARCHAR(255) NOT NULL,
  `Observacoes` TEXT NULL DEFAULT NULL,
  `ID_Fornecedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Evento`),
  INDEX `ID_Reserva_idx` (`ID_Reserva` ASC) VISIBLE,
  INDEX `ID_Fornecedor_idx` (`ID_Fornecedor` ASC) VISIBLE,
  CONSTRAINT `ID_Fornecedor`
    FOREIGN KEY (`ID_Fornecedor`)
    REFERENCES `mydb`.`fornecedores` (`ID_Fornecedor`),
  CONSTRAINT `ID_Reserva`
    FOREIGN KEY (`ID_Reserva`)
    REFERENCES `mydb`.`reservas` (`ID_Reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
  `ID_Pagamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Reserva` INT UNSIGNED NOT NULL,
  `Valor` DECIMAL(10,2) UNSIGNED NOT NULL,
  `Método_Pagamento` ENUM('Credito', 'Debito', 'Pix', 'Outro') NOT NULL,
  `Data_Pagamento` DATE NOT NULL,
  `Status_Pagamento` ENUM('Pendente', 'Cancelado', 'Pago', 'Processando') NOT NULL,
  PRIMARY KEY (`ID_Pagamento`),
  INDEX `ID_Reserva_idx` (`ID_Reserva` ASC) VISIBLE,
  CONSTRAINT `FK_Pagamentos_Reservas`
    FOREIGN KEY (`ID_Reserva`)
    REFERENCES `mydb`.`reservas` (`ID_Reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
